### ISSUE TITLE
Use pint for unit conversion

### ISSUE THREAD

**Issue by cristinasewell** [pcdshub/pcdscalc#10]
Consider relying on pint for unit conversion.

## Current Behavior
Using a dictionary `units` in the constants module.

## Possible Solution
As we do it in `pcdsdevices`:
https://github.com/pcdshub/pcdsdevices/blob/5ee91018658423b297e17a242f72b09bfcefc87e/pcdsdevices/utils.py#L93-L122

**Comment by tangkong** [comment]
Given the recent trouble we've had with `pint` and our decision to move away from it, I'm going to close this issue
