### ISSUE TITLE
Dependency doctr-versions-menu is now docs-version-menu

### ISSUE THREAD

**Issue by klauer** [pcdshub/pcdscalc#11]
https://github.com/pcdshub/pcdscalc/blob/cf76a13115a56264387dd3184de32192657c2226/doc-requirements.txt#L3

Dependencies and sphinx config need updating.
Old: https://pypi.org/project/doctr-versions-menu/
New: https://pypi.org/project/docs-versions-menu/
Repository: https://github.com/goerz/docs_versions_menu/

**Comment by ZLLentz** [comment]
closed in #22
